version: '3.9'

services:
  flask-app-sessions:
    build: ./app
    image: learning_team/flask_app_sessions:latest
    container_name: my-flask-app-sessions
    ports:
      - 5000:5000
    volumes:
      - ./app:/app # Temporal NOT use in production
