version: "3.9"

services:
  web:
    image: 
    ports:
      - "8080:80"
    #volumes:
    #  - "api-consumer-cache:/api-cache"
    volumes:
      - ./src/test:/app/test # mount point
    networks:
      - api-consumer-net
#volumes:
#  api-consumer-cache:
networks:
  api-consumer-net:

