version: "3.7"
services:
  cpp_os_base:
    build:
      context: ./../
      dockerfile: docker_base_images/os/Dockerfile
    image: cpp_poco/ubuntu_base:latest
    container_name: ubuntu_base
  cpp_cuda_base:
    build:
      context: ./../
      dockerfile: docker_base_images/cuda/Dockerfile
    image: cpp_poco/cuda_base:latest
    container_name: cuda_base
    depends_on:
      - cpp_os_base
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
            count: all
  cpp_poco_base:
    build:
      context: ./../
      dockerfile: docker_base_images/poco/Dockerfile
    image: cpp_poco/poco_base:latest
    container_name: poco_base
    depends_on:
      - cpp_cuda_base
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
            count: all